### ISSUE TITLE
Timeout po "Logging in..."

### ISSUE THREAD

**Issue by Crawcik** [PanSzelescik/instaling-bot#3]
const timeoutError = new Errors_js_1.TimeoutError(`waiting for ${options.title} failed: timeout ${options.timeout}ms exceeded`);
                                 ^

TimeoutError: waiting for selector `#main-container > div:nth-child(2) > form > div > div:nth-child(3) > button` failed: timeout 8000ms exceeded
    at new WaitTask (/home/crawcik/instaling-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
    at DOMWorld.waitForSelectorInPage (/home/crawcik/instaling-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26)
    at Object.internalHandler.waitFor (/home/crawcik/instaling-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/home/crawcik/instaling-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29)
    at Frame.waitForSelector (/home/crawcik/instaling-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
    at Page.waitForSelector (/home/crawcik/instaling-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1280:33)
    at checkVisibility (/home/crawcik/instaling-bot/src/helpers.js:57:17)
    at click (/home/crawcik/instaling-bot/src/helpers.js:22:11)
    at login (/home/crawcik/instaling-bot/src/main.js:60:11)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by PanSzelescik** [comment]
Zaktualizuj bota (`git pull` i `npm install`), naprawiałem to w https://github.com/PanSzelescik/instaling-bot/commit/158de28af4c9eab7a4d8b3745466a72a5294e735

**Comment by Crawcik** [comment]
Bruh nie 
![obraz](https://user-images.githubusercontent.com/42977680/117648413-774dec80-b18e-11eb-8c83-727537ecbe31.png)

**Comment by PanSzelescik** [comment]
Na pewno jesteś na najnowszym commicie na masterze? Błędy wskazują że nadal masz nieaktualną wersję 🤔

**Comment by Crawcik** [comment]
O boże, zły branch mi pokazywało XD
